name: Build and deploy Python project to Azure Function App - trading-bot-v3

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies locally for Azure
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Zip everything (Forces inclusion of hidden .python_packages folder)
        shell: bash
        run: |
          zip -r package.zip . -x "*.git*" -x "*venv*"
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DEA363D0DA2941B7942C9FDD131C44FE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FF48BF53AED04ECBAAD8196EA9561D41 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3E345A8230BF4EF2B278CF52C520E4C2 }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'trading-bot-v3'
          slot-name: 'Production'
          package: 'package.zip'
          
